-- Live Floor queue order ---------------------------------------------------
-- The floor board grows up/down arrows on a queued job. They cannot write
-- job_cards.queue_pos: that column is ONE number per job card, shared by every
-- section, and it is what Print Planning writes when a press lane is dragged
-- (production.js:665) — so a move at die cutting would silently reshuffle a
-- planner's press lane.
--
-- floor_pos is per STAGE and is written only by POST /floor/queue/move. NULL
-- means the job has never been reordered on the floor. It is an OVERRIDE, not
-- an absolute rank: floor-order.js ranks an unstamped row where the plant's own
-- order (queue_pos, then delivery date) would have put it, and only ever
-- compares floor_pos between rows in the SAME lane. So an untouched plant keeps
-- exactly the order it has today, and a job booked after someone reordered a
-- lane still lands on its own merits instead of sinking below the whole lane.
ALTER TABLE job_stages ADD COLUMN IF NOT EXISTS floor_pos INTEGER;
